import { Boxes, Building2, HandCoins, Handshake, Target, TrendingUp, Users2 } from 'lucide-react'
import { DashSection } from '@/components/dashboard/dashboard-shell'
import { Card, Badge } from '@/components/kit/primitives'
import { MetricCard } from '@/components/kit/metric-card'
import { AIInsightCard } from '@/components/kit/ai-cards'
import { LifecycleTracker } from '@/components/kit/lifecycle-tracker'
import { BarList } from '@/components/kit/charts'
import { IndustryHub } from '@/components/kit/industry-collaboration'
import { getChallenges, getProjects } from '@/lib/services'

export const metadata = { title: 'Industry Partnership Hub' }

const csrByDomain = [
  { label: 'Water', value: 18, hint: 'L committed' },
  { label: 'Agriculture', value: 12, hint: 'L committed' },
  { label: 'Energy', value: 8, hint: 'L committed' },
  { label: 'Healthcare', value: 4, hint: 'L committed' },
]

const partners = [
  { name: 'BIT Mesra, Ranchi', type: 'Academic partner', role: 'Research & student teams', projects: 3 },
  { name: 'NIT Jamshedpur', type: 'Academic partner', role: 'Sensor & IoT labs', projects: 2 },
  { name: 'Dept. of Drinking Water & Sanitation', type: 'Government', role: 'Deployment & scale-up', projects: 4 },
  { name: 'SolarGrid MSME Cluster', type: 'Supply partner', role: 'Hardware & installation', projects: 2 },
]

export default async function IndustryDashboard() {
  const opportunities = (await getChallenges())
    .filter((c) => ['Water', 'Agriculture', 'Energy', 'Healthcare'].includes(c.domain))
    .slice(0, 4)
  const projects = getProjects()

  return (
    <div className="mx-auto max-w-6xl space-y-10">
      <DashSection
        id="overview"
        title="AgriSense Technologies — Partnership Hub"
        description="Discover challenges aligned to your CSR mandate, contribute resources, and track pilot outcomes."
      >
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <MetricCard icon={Target} value="18" label="Aligned opportunities" tone="pink" />
          <MetricCard icon={Handshake} value="6" label="Active partnerships" tone="sage" />
          <MetricCard icon={HandCoins} value="₹42L" label="Resources committed" tone="peach" />
          <MetricCard icon={TrendingUp} value="3" label="Pilots scaled" tone="cream" />
        </div>
      </DashSection>

      {/* CSR-aligned opportunities + resource matching + my offers */}
      <IndustryHub opportunities={opportunities} />

      {/* Contributions / sponsored projects */}
      <DashSection id="sponsorships" title="Sponsored Projects" description="Live projects where your organization is a contributing partner.">
        {projects.map((p) => (
          <Card key={p.id} className="p-6">
            <div className="flex flex-wrap items-start justify-between gap-3">
              <div>
                <Badge tone="forest">{p.status}</Badge>
                <h3 className="mt-2 font-serif text-xl font-bold text-forest-deep">{p.title}</h3>
                <p className="mt-1 text-sm text-muted-foreground">
                  {p.university} · {p.team}
                </p>
              </div>
              <Badge tone="outline" className="font-mono text-[0.7rem]">
                {p.id}
              </Badge>
            </div>
            <div className="mt-4 grid gap-3 sm:grid-cols-3">
              {[
                { icon: HandCoins, label: 'Funding', value: '₹8L committed' },
                { icon: Boxes, label: 'Hardware', value: 'IoT sensor kits' },
                { icon: Handshake, label: 'Mentorship', value: 'Domain expert assigned' },
              ].map((r) => (
                <div key={r.label} className="flex items-center gap-2.5 rounded-xl bg-muted/50 p-3">
                  <span className="grid size-9 place-items-center rounded-lg bg-secondary/12 text-secondary">
                    <r.icon className="size-4.5" />
                  </span>
                  <div>
                    <div className="text-[0.7rem] text-muted-foreground">{r.label}</div>
                    <div className="text-sm font-semibold text-forest-deep">{r.value}</div>
                  </div>
                </div>
              ))}
            </div>
            <div className="mt-5">
              <LifecycleTracker steps={p.timeline} compact />
            </div>
          </Card>
        ))}
      </DashSection>

      {/* CSR impact */}
      <DashSection id="impact" title="CSR Impact" description="Measurable social return generated by your committed resources.">
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <MetricCard icon={TrendingUp} value="18,600+" label="People reached" tone="pink" />
          <MetricCard icon={HandCoins} value="₹42L" label="Resources deployed" tone="sage" />
          <MetricCard icon={Boxes} value="3" label="Pilots scaled to deployment" tone="peach" />
          <MetricCard icon={Handshake} value="6" label="Active collaborations" tone="cream" />
        </div>
        <Card className="mt-4 p-6">
          <h3 className="mb-4 font-serif text-base font-semibold text-forest-deep">CSR contribution by domain (₹ lakh)</h3>
          <BarList data={csrByDomain} suffix="" />
        </Card>
      </DashSection>

      {/* Partnership ecosystem */}
      <DashSection id="partnerships" title="Partnership Ecosystem" description="Universities, government bodies, and supply partners you collaborate with.">
        <div className="grid gap-4 sm:grid-cols-2">
          {partners.map((p) => (
            <Card key={p.name} className="flex items-start gap-3 p-5">
              <span className="grid size-10 shrink-0 place-items-center rounded-xl bg-secondary/12 text-secondary">
                {p.type === 'Academic partner' ? (
                  <Building2 className="size-5" />
                ) : p.type === 'Government' ? (
                  <Handshake className="size-5" />
                ) : (
                  <Boxes className="size-5" />
                )}
              </span>
              <div className="min-w-0 flex-1">
                <div className="flex items-start justify-between gap-2">
                  <h3 className="font-serif text-base font-semibold text-forest-deep">{p.name}</h3>
                  <Badge tone="outline" className="shrink-0 text-[0.7rem]">
                    {p.projects} projects
                  </Badge>
                </div>
                <p className="mt-0.5 text-xs font-medium uppercase tracking-wide text-muted-foreground">{p.type}</p>
                <p className="mt-1 inline-flex items-center gap-1.5 text-sm text-foreground/80">
                  <Users2 className="size-3.5 text-muted-foreground" /> {p.role}
                </p>
              </div>
            </Card>
          ))}
        </div>
      </DashSection>

      <DashSection id="ai" title="AI Recommendation">
        <AIInsightCard title="High-ROI impact opportunity">
          Committing solar backup hardware to 2 Energy challenges in Palamu would strengthen 3 of your existing water
          pilots (shared infrastructure) and reach an estimated{' '}
          <span className="font-semibold text-forest-deep">6,400 additional people</span>.
        </AIInsightCard>
      </DashSection>
    </div>
  )
}
